runtime: php55
api_version: 2
threadsafe: true
handlers:
- url: /
  script: index.php
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /ajax
  static_dir: ajax
- url: /js
  static_dir: js
- url: /*
  script: index.php